language:
  minimal

services:
  docker

install:
  make install

script:
  make build

deploy:
  provider: script
  script: make deploy
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH != *-alpha
