language:
  minimal

services:
  docker

install:
  make install

script:
  make build

deploy:
  provider: script
  script: make deploy
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH != *-alpha

notifications:
  slack:
    secure: aAEZulVSQQ6/3FeKoZyMxotxA+PV/3zMstg4CCBqLku403AwT/3UyQdyxODTIotV2o4gR9jfKZdMhUYmdLrZuGCDmUYZXeM4c9UEI3ReN0R2cFdIsyQK7DV8MhnqrOOoRjY1YwaqpXViMDodvwFBDPv5yzCJjxwupLR2E8rtw8PWyC6JEQbHL/JACkfQZhVZXNbiFuVr8bxtIM6NOUhntRCyK78azDqK7j6f5BICxVI8IPJ7toy5jJa8b6S7qNX049xH7feZ9p5J92KQFHXO3HYDCy+NtzQpJxQvejhevgT6FLFyVj7KBl93xwre+6y2DxMgkVt4Vq/hQZAQjmsxvAryM5zUMJuwfbIwPZvfMUNHbPiTk4J0C1jASZFPJKA5PNn3Qiil6Y/8NeT7QlM9/YNdmJR2eFBgILtit2oplvelMi7wO6JBUAPpWoXSTkKN0Am7m/hsb09KysvymVHhjVJIcrw2Yi7kyDPuvYo4eLXsB1yTWTjyEbSC8IpfXzYLTtK3wR+7sX8Xsw0/SZZy5mujvO7pTsVodvJQqj/cswQzYxJHQACTVg2epzcHlCYa28z9d4GN+tvw9KWW/ScKty5Qe+pT5fz6CA9xxHSU2UNh7HQfB07Y2m39M+U18Y8WLM4ELqI3BwRDTJN/ZdK1Fsxmph+Rcxun2sUSK98ddIw=
